vasco_user:
    resource: "@VascoUserBundle/Resources/config/routing.yml"
    prefix:   /

vasco_crud:
    resource: "@VascoCrudBundle/Controller/"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_user_registration_confirmed:
    path:      /login
    defaults:  { _controller: FOSUserBundle:Security:login }
