<?php

namespace Vasco\CrudBundle\Repository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * JUST FOR TEST PURPOSE
 */
class TestRepository extends \Doctrine\ORM\EntityRepository
{
}
